### ISSUE TITLE
Linters runner problem

### ISSUE THREAD

**Issue by DRT-DISABLED-ACCOUNT** [Vishal30M/Portfolio#8]
### 👋Hey Vishal

Try updating the runner version to `ubuntu-22.04`

https://github.com/Vishal30M/Portfolio/blob/09e20413e4806b1aa7ce344efab0a0d42c7f3738/.github/workflows/linters.yml#L11

👇e.g. 

Make sure that you update the `runner` on the jobs, webhint, styleint, and nodechecker.

```yaml
name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  lighthouse:
    name: Lighthouse
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Setup Lighthouse
        run: npm install -g @lhci/cli@0.7.x
      - name: Lighthouse Report
        run: lhci autorun --upload.target=temporary-public-storage --collect.staticDistDir=.
  webhint:
    name: Webhint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Setup Webhint
        run: |
          npm install --save-dev hint@7.x
          [ -f .hintrc ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/html-css/.hintrc
      - name: Webhint Report
        run: npx hint .
  stylelint:
    name: Stylelint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Setup Stylelint
        run: |
          npm install --save-dev stylelint@13.x stylelint-scss@3.x stylelint-config-standard@21.x stylelint-csstree-validator@1.x
          [ -f .stylelintrc.json ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/html-css/.stylelintrc.json
      - name: Stylelint Report
        run: npx stylelint "**/*.{css,scss}"
  nodechecker:
    name: node_modules checker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Check node_modules existence
        run: |
          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set up a .gitignore file with this folder included on it to prevent this from happening in the future." && exit 1; fi
```

If updating the `linters.yaml` configuration file with the appropriate runner version does not resolve the issue, you could try upgrading your Ubuntu version 👇

```
sudo apt update && sudo apt upgrade -y
```

I hope it works, if you need anything please write me in telegram or slack t.me/sudodrt 👍
